service: default
runtime: nodejs10
env: standard
instance_class: F1

automatic_scaling:
    max_instances: 2
    target_cpu_utilization: 0.95

handlers:
    - url: /.*
      script: auto
      secure: always
      redirect_http_response_code: 301
